# Generated by Django 5.0.6 on 2024-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manproducts',
            name='product_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manproducts',
            name='product_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
