# Generated by Django 5.0.6 on 2024-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_manproducts_product_colour_manproducts_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manproducts',
            name='product_size',
            field=models.CharField(choices=[('X', 'Extra Small'), ('Sm', 'Small'), ('L', 'Large')], default='Sm', max_length=4),
        ),
    ]
