# Generated by Django 5.0.6 on 2024-07-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.manproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
            ],
        ),
    ]
